class Constants:
    kindA = 'Unit'
    kindAGen = 'units'
    kindB = 'Legion'
    kindBGen = 'legions'
    kindC = 'User'
    kindCGen = 'users'
    ALREADY_ASSIGNED = 'This ' + kindA + ' is already assigned to a ' + kindB
    BAD_METHOD = 'Method not allowed'
    BEARER_ERR = 'Bearer token malformed'
    CANNOT_DELETE_UNIT = 'Cannot delete ' + kindA + ' associated with a ' + kindB
    DOCUMENTATION = ''
    ENTITY_NOT_FOUND = 'This ' + kindA + ' or ' + kindB + ' does not exist'
    EXTRA_ATTRIBUTES = 'Unrecognized attributes in request'
    ID_MISMATCH = 'The owner_id does not match the id in the token'
    ID_UPDATE = 'Cannot set id attribute'
    INCOMPLETE = 'The request object is missing at least one of the required attributes'
    INVALID_DATA = 'Invalid data for at least one of the required attributes'
    INVALID_METHOD = 'Method is not allowed'
    INVALID_TOKEN = 'Invalid token'
    MIME_ERR = 'Unsupported mimetype in request'
    NOT_EXISTS = 'does not exist'
    NO_ID = 'Invalid id'
    NO_TOKEN = 'Missing token'
    RELATIONSHIP_NOT_FOUND = 'This ' + kindA + ' is not part of this ' + kindB
    TOKEN_UNAUTHORIZED = 'Token not authorized to modify entity'
    UNKNOWN_AUTH = 'Unknown authorization error'
    limit = 5
    minStringLength = 3
    maxNameLength = 255
    maxCategoryLength = 255
    startingBudget = 1000
    NUM_KINDA_ATTRIBUTES = 4
    NUM_KINDB_ATTRIBUTES = 3
    validChars = '^[a-zA-Z0-9 ]+$'

    AUTH_SCOPES = ['https://www.googleapis.com/auth/userinfo.email', 'openid',
             'https://www.googleapis.com/auth/userinfo.profile']
    AUTH_ISSUER = 'accounts.google.com'
    TERRAINS = ["desert","mountains","plains","tundra","wetlands"]